# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20160906_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insumos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
