# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20160906_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='direccion',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
