# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0029_auto_20161023_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
