# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0034_auto_20161028_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilios',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='domicilios',
            name='latitud',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='longitud',
            field=models.CharField(default='', max_length=50),
        ),
    ]
