# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0035_auto_20161028_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cont', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Det_Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ins', models.CharField(max_length=20)),
                ('cantidad', models.FloatField()),
                ('cont_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Contenido')),
            ],
        ),
    ]
