# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0036_contenido_det_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Contenido'),
        ),
    ]
