# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0038_auto_20161102_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copia_DetRem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_id2', models.IntegerField()),
                ('ins_id2', models.IntegerField()),
                ('cant_recib2', models.IntegerField()),
                ('vencimiento2', models.DateField(default=datetime.date.today)),
                ('codigo2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Copia_Remitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_id2', models.CharField(max_length=50)),
                ('dep_id2', models.IntegerField()),
                ('fecha_recib2', models.DateField(default=datetime.date.today)),
                ('codigo2', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='remitos',
            name='fact_id',
        ),
        migrations.AddField(
            model_name='detalle_remito',
            name='vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='insumos',
            name='codigo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remitos',
            name='codigo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remitos',
            name='dep_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Depositos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='copia_detprod',
            name='capacidad2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle_produccion',
            name='capacidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle_remito',
            name='cant_recib',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='otro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='remitos',
            name='fecha_recib',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
