# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0040_auto_20161111_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='capacidad',
            field=models.FloatField(),
        ),
    ]
