# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 03:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20160906_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecnac',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
