# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20160922_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='cuentacorriente',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cuit',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
