# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_auto_20161022_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formapago', models.CharField(default='Efectivo', max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('total', models.FloatField(default=0.0)),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Clientes')),
                ('direccion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Domicilios')),
                ('pedido', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Pedidos')),
                ('rep_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='repartidorventa', to='principal.Empleados')),
            ],
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='art',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Ventas'),
        ),
    ]
