# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_auto_20161022_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta_SinPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formapago', models.CharField(default='Efectivo', max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('total', models.FloatField(default=0.0)),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Clientes')),
                ('direccion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Domicilios')),
                ('rep_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='repartidorventa', to='principal.Empleados')),
            ],
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cli_id',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='formapago',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='rep_id',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='total',
        ),
    ]
