# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_auto_20161023_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta_SinPedido',
            new_name='VentaSinPedido',
        ),
    ]
