# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_auto_20161023_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.VentaSinPedido'),
        ),
    ]
