# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0027_auto_20161023_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='sinpedido',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.VentaSinPedido'),
        ),
    ]
