# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0030_pedidos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Pedidos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='sinpedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.VentaSinPedido'),
        ),
    ]
