# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0031_auto_20161023_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcamion',
            name='cam_id',
        ),
        migrations.AddField(
            model_name='stockcamion',
            name='emp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Empleados'),
            preserve_default=False,
        ),
    ]
