# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo_Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_ult_comp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envase', models.CharField(max_length=10)),
                ('capacidad', models.CharField(max_length=5)),
                ('contenido', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecAdquisicion', models.DateField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=13)),
                ('fecAlta', models.DateField(default=datetime.date.today)),
                ('dni', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_recib', models.IntegerField()),
                ('precio_unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Remito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_recib', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=30)),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecInicio', models.DateField()),
                ('fecFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('fecIng', models.DateField(default=datetime.date.today)),
                ('fecNac', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recib', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumo_Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_ult_comp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Reparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Clientes')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecInicio', models.DateField()),
                ('fecFin', models.DateField()),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=13)),
                ('cuit', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Remitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recib', models.DateField()),
                ('fact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Facturas')),
                ('prov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Repartos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Camiones')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleados')),
            ],
        ),
        migrations.CreateModel(
            name='StockArticulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Depositos')),
            ],
        ),
        migrations.CreateModel(
            name='StockCamion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos')),
                ('cam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Camiones')),
            ],
        ),
        migrations.CreateModel(
            name='StockInsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Depositos')),
                ('ins_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Insumos')),
            ],
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='pedido_reparto',
            name='ped_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pedidos'),
        ),
        migrations.AddField(
            model_name='pedido_reparto',
            name='rep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Repartos'),
        ),
        migrations.AddField(
            model_name='insumo_proveedor',
            name='ins_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Insumos'),
        ),
        migrations.AddField(
            model_name='insumo_proveedor',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Proveedores'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Proveedores'),
        ),
        migrations.AddField(
            model_name='empleado_zona',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleados'),
        ),
        migrations.AddField(
            model_name='empleado_zona',
            name='zona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Zonas'),
        ),
        migrations.AddField(
            model_name='detalle_remito',
            name='ins_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Insumos'),
        ),
        migrations.AddField(
            model_name='detalle_remito',
            name='rem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Remitos'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='ped_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pedidos'),
        ),
        migrations.AddField(
            model_name='detalle_factura',
            name='fact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Facturas'),
        ),
        migrations.AddField(
            model_name='detalle_factura',
            name='ins_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Insumos'),
        ),
        migrations.AddField(
            model_name='articulo_proveedor',
            name='art_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos'),
        ),
        migrations.AddField(
            model_name='articulo_proveedor',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Proveedores'),
        ),
    ]
