# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_empleados_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='fecNac',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
