# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_auto_20161019_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='otro',
            field=models.IntegerField(default=0),
        ),
    ]
