# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='articulos',
            name='existenciamin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulos',
            name='nombre',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
