# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20160921_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
