# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20160922_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='envios',
            field=models.BooleanField(default=False),
        ),
    ]
