# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_proveedores_envios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='formapago',
            field=models.CharField(default='Efectivo', max_length=10),
        ),
    ]
