# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20161004_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copia_DetProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reg2', models.DateField(default=datetime.date.today)),
                ('cantidad2', models.IntegerField()),
                ('capacidad2', models.IntegerField()),
                ('articulo_reg2', models.IntegerField()),
                ('tipo_reg2', models.IntegerField()),
                ('deposito2', models.IntegerField()),
                ('estado_reg2', models.BooleanField(default=True)),
                ('fecha_vto2', models.DateField(default=datetime.date.today)),
                ('fecha_env2', models.DateField(default=datetime.date.today)),
                ('lote2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Det_Rec_Ins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reg', models.DateField(default=datetime.date.today)),
                ('cantidad', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('tipo_reg', models.IntegerField()),
                ('deposito', models.IntegerField()),
                ('fecha_vto', models.DateField(default=datetime.date.today)),
                ('fecha_env', models.DateField(default=datetime.date.today)),
                ('lote', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='insumos',
            name='otro',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumos',
            name='tipo',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='direccion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Domicilios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(default='-', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='detalle_produccion',
            name='articulo_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos'),
        ),
        migrations.AddField(
            model_name='det_rec_ins',
            name='art_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos'),
        ),
        migrations.AddField(
            model_name='det_rec_ins',
            name='ins_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Insumos'),
        ),
    ]
