# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20161019_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='nombre',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
