# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20161001_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cuit',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
