# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20161019_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle_remito',
            name='cant_recib',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockarticulos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockcamion',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockinsumos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
