# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_auto_20161020_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Articulos')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='domicilios',
            name='direccion',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
