# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_ventas_sinpedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precios',
            name='art_id',
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Precios',
        ),
    ]
