# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0033_necesidadcamion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilios',
            name='coordenadas',
            field=models.CharField(max_length=70),
        ),
    ]
