# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20161019_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='direccion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Domicilios'),
        ),
    ]
