# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0041_auto_20161110_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='enruta',
            field=models.BooleanField(default=False),
        ),
    ]
